import { QuizResult } from './quiz-engine';
import { personalityProfiles, ColorKey, colorHex } from './personality-data';

// Convert hex to RGB values for jsPDF
function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

export const generateReport = async (result: QuizResult) => {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();
  const profile = personalityProfiles[result.dominant];
  const [dr, dg, db] = hexToRgb(colorHex[result.dominant]);

  // Header bar with dominant color
  doc.setFillColor(dr, dg, db);
  doc.rect(0, 0, 210, 12, 'F');

  // Title
  doc.setFontSize(26);
  doc.setTextColor(dr, dg, db);
  doc.text('ColSync', 20, 30);
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text('Personality Report', 62, 30);

  // Divider
  doc.setDrawColor(dr, dg, db);
  doc.setLineWidth(0.5);
  doc.line(20, 35, 190, 35);

  // Dominant + Motivation
  doc.setFontSize(16);
  doc.setTextColor(dr, dg, db);
  doc.text(`${profile.name} Personality`, 20, 48);
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.text(`Core Motivation: ${profile.motive}`, 20, 56);

  // Summary
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  const summaryLines = doc.splitTextToSize(profile.summary, 170);
  doc.text(summaryLines, 20, 66);

  let y = 66 + summaryLines.length * 5 + 10;

  // Color Distribution with colored bars
  doc.setFontSize(13);
  doc.setTextColor(40, 40, 40);
  doc.text('Color Distribution', 20, y);
  y += 8;

  (Object.keys(result.scores) as ColorKey[]).forEach((key) => {
    const [r, g, b] = hexToRgb(colorHex[key]);
    const pct = result.percentages[key];

    // Color bar background
    doc.setFillColor(240, 240, 240);
    doc.roundedRect(50, y - 4, 100, 5, 1, 1, 'F');

    // Color bar fill
    doc.setFillColor(r, g, b);
    doc.roundedRect(50, y - 4, pct, 5, 1, 1, 'F');

    // Label
    doc.setFontSize(9);
    doc.setTextColor(r, g, b);
    doc.text(`${personalityProfiles[key].name}`, 20, y);
    doc.setTextColor(100, 100, 100);
    doc.text(`${result.scores[key]} (${pct}%)`, 155, y);

    y += 9;
  });

  y += 5;

  // Strengths
  doc.setFontSize(13);
  doc.setTextColor(dr, dg, db);
  doc.text('Strengths', 20, y);
  y += 7;
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  profile.strengths.forEach((s) => {
    doc.setFillColor(dr, dg, db);
    doc.circle(24, y - 1.5, 1.5, 'F');
    doc.text(s, 28, y);
    y += 5.5;
  });

  y += 4;

  // Growth Areas
  doc.setFontSize(13);
  doc.setTextColor(100, 100, 100);
  doc.text('Growth Areas', 20, y);
  y += 7;
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  profile.limitations.forEach((l) => {
    doc.setFillColor(180, 180, 180);
    doc.circle(24, y - 1.5, 1.5, 'F');
    doc.text(l, 28, y);
    y += 5.5;
  });

  y += 4;

  // Career Style
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFontSize(13);
  doc.setTextColor(dr, dg, db);
  doc.text('Career Style', 20, y);
  y += 7;
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  const careerLines = doc.splitTextToSize(profile.careerStyle, 170);
  doc.text(careerLines, 20, y);
  y += careerLines.length * 5 + 5;

  // Ideal Roles
  doc.setFontSize(13);
  doc.setTextColor(dr, dg, db);
  doc.text('Ideal Roles', 20, y);
  y += 7;
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  profile.idealRoles.forEach((r) => {
    doc.setFillColor(dr, dg, db);
    doc.circle(24, y - 1.5, 1.5, 'F');
    doc.text(r, 28, y);
    y += 5.5;
  });

  // Footer bar
  doc.setFillColor(dr, dg, db);
  doc.rect(0, 285, 210, 12, 'F');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text('Generated by ColSync - colsync.com', 20, 290);

  doc.save('ColSync_Report.pdf');
};
